### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by Sanqui** [rednex/rgbds#144]
```
sanky@suguri:~/romhacking/gb/rgbds/test/asm$ sh test.sh 
--- /tmp/tmp.PP2NRvj9ZZ	2017-03-26 12:25:42.630535663 +0200
+++ bank-noexist.out	2017-01-26 10:41:36.388515238 +0100
@@ -0,0 +1,2 @@
+ERROR:	bank-noexist.asm(2) :
+	'noexist' not defined
--- /tmp/tmp.PP2NRvj9ZZ	2017-03-26 12:25:42.659536028 +0200
+++ null-in-macro.out	2017-01-26 10:41:36.389515247 +0100
@@ -1,2 +0,0 @@
-ERROR:	null-in-macro.asm(1) :
-	Unterminated MACRO definition
--- /tmp/tmp.PP2NRvj9ZZ	2017-03-26 12:25:42.662536066 +0200
+++ undefined-dot.out	2017-01-26 10:41:36.389515247 +0100
@@ -1,3 +1,2 @@
 ERROR:	undefined-dot.asm(3) :
 	'.' not defined
-../../rgbasm: Assembly aborted in pass 2 (1 errors)!
sanky@suguri:~/romhacking/gb/rgbds/test/asm$ 
```

The current method of running tests is also quite crude, I'm not convinced there's need for a replacement.

**Comment by AntonioND** [comment]
Well, 2 of them are failing because they have been fixed and the other one still fails the same way.

- The first one was fixed here: https://github.com/rednex/rgbds/pull/16 The error should now be at link time.
- The second one was fixed here: https://github.com/rednex/rgbds/pull/119
- The third one is just a change in the error message that adds more information.

The current system could be improved, yes.

**Comment by AntonioND** [comment]
Fixed here: https://github.com/rednex/rgbds/commit/f63339472e0de6281f61ef0c8eea7ca181fa298a

I've created this issue: https://github.com/rednex/rgbds/issues/151
