### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by Sanqui** [rednex/rgbds#185]
Right now it's difficult to tell the version of rgbds tools installed.  This is [inconvenient](https://github.com/pret/pokecrystal/pull/360#issuecomment-310917700).

**Comment by AntonioND** [comment]
Yeah, I guess this is something that we actually need... I'm just worried about having the same version number in all the commits between versions, so I'll add some git magic to the Makefile to use a dirty indicator (```git describe``` should be good enough for this), if that's ok with you.

**Comment by Sanqui** [comment]
`git describe` sounds good to me!

**Comment by AntonioND** [comment]
Hmmmm... There's a problem with this. My idea was to add something like this to the code:
```
#ifndef VERSION
#define VERSION "v0.3.4"
#endif
```
And do something like this in the makefile:
```
-DVERSION=`git describe 2>/dev/null`
```
That way, if the `.git` folder isn't present, it has the default version number. If it's there, it will use something a bit more descriptive.

I might just leave a text string in the source code (and maybe introduce patch level to the version string), because any kind of conditional execution in a Makefile isn't portable, it would only run in BSD make or GNU make...

**Comment by AntonioND** [comment]
Of course, the sooner I say I can't do it the sooner I find a way of doing it... xD

**Comment by AntonioND** [comment]
I have a problem, though. `rgbasm`, `rgbfix` and `rgbgfx` already use `-v` for something. I could either:

1. Move the `-v` to a different character and then use `-v` for `--version`. This breaks compatibility.
2. Make `--version` a different option than `-v`. This is not a standard behaviour.
3. Move the version string to a character that isn't used for now, like `-z`.

For 1 and 2 it is needed to stop using `getopt` and use `getopt_long` instead.

My preferred option is 3, but I'm not sure about it.

**Comment by Ben10do** [comment]
Hmm... Personally, I think that it goes without saying that 3 would be *very* non-standard.

I personally think 2 is the best option - it retains compatibility, and is still obvious. I don't have a computer to hand to check, but I'm sure I've seen examples of this behaviour in other programs.

I know it'd be more work to transition to `getopt_long`, but I think now's the time to do so 😉

**Comment by cesarmiquel** [comment]
Indeed git works that way:

```
miquel@zen:~$ git --version
git version 2.11.0
miquel@zen:~$ git -v
Unknown option: -v
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by AntonioND** [comment]
Yeah, it is *really* non-standard.

I've seen some programs do that too, but they are usually programs that have dozens of options, so they don't really have a choice. But then again, it's probably the only way to keep it backwards-compatible and logical at the same time...

So far I have a piece of code that uses a predefined string in the source code if a git folder isn't present, and the output of `git describe` if it is there.

**Comment by AntonioND** [comment]
I'm not too sure about the `git describe` thing, though... I mean, you can still rebuild the exact same binary every time, it's not time-dependent or anything (and if you lose the `.git` folder you can't go back in time in the source code, so it doesn't matter anyway). I'm just not sure if it's worth the effort.

It seems to me that it's a bit nicer in the sense that you don't need to create a new tag/release every time a new patch is applied (that is a bit overkill in my opinion) because git describe does it automatically. However, if you checkout the code and delete the `.git` folder, you lose the information.

Maybe it's worth starting to update the patch version (or add a new level to the version number) every time a patch is applied? What about having a development branch that holds a few changes and then master is updated to point at it when a few patches have been applied?

Or maybe just forget all this and just have the version of the previous release until the next one. But that is a lie and if there is a compatibility break and the number isn't immediately updated, the version number will be useless.

**Comment by bentley** [comment]
It’s not uncommon to provide a version flag that is not `-v`. avahi, bzip2, curl, inkscape, lz4, pcregrep, vorbiscomment, and wget (not especially obscure programs) use `-V`.

`-v` for validate is not ideal, but I don’t think the flag that literally everybody uses rgbfix for should be changed now.

getopt_long is nonstandard.

**Comment by bentley** [comment]
I don’t dislike the concept of a version flag, but can we think about it for a bit and make sure it’s the right thing?

I can think of two cases where a version flag would be useful. One is if I want to check if I’m on the latest version. (Maybe this would help others, but I would check my downloads folder for the original tarball, or just build from Git.)

The other is if RGBDS version incompatibility may be causing a build problem. The flag only helps here if I know (or am told) that this kind of thing can happen, *and* I have the ability to figure out what has changed in different versions to cause my problem. Most people don’t follow RGBDS development and won’t be able to do this.

Would an assembler directive that allows projects to request a minimum version be more effective at solving this?

**Comment by AntonioND** [comment]
I think that maybe we should have both, the directive and the flag, to be honest. They just have different uses.

I didn't realize that `getopt_long` was a GNU extension. I suppose that the other option is to use `-V` for this and leave `-v` for what it is used now.

**Comment by AntonioND** [comment]
Ok, I've switched to `-V`.
