### ISSUE TITLE
can't subtract in `set` statements

### ISSUE THREAD

**Issue by yenatch** [rednex/rgbds#222]
been meaning to report this for some time. either of the following produce a syntax error:
```
x = y - 5
x set y - 5
```

the following does work however:
```
x = y + -5
```

**Comment by AntonioND** [comment]
This seems to be caused by the two following lines:

https://github.com/rednex/rgbds/blob/8954858bf79a9ad48eacb063d42b47882ede1175/src/asm/asmy.y#L1150-L1156

I added the second line (even though I knew there was a syntax conflict) to fix another problem. If you subtract two labels, the result is known if:
- Both symbols are labels in sections with fixed base address (so they are known at assembly time).
- Both symbols are labels in the same section, even without a fixed base address (the value isn't known at assembly time, but the difference is).
- Both symbols are constant (known at assembly time).

However, without the check, this would also work in the following case:
- Both symbols are labels in different sections, and at least one of them doesn't have a fixed base address.

However, I'd swear I've seen this problem long before the patch that introduced the check.

**Comment by AntonioND** [comment]
Yes, this bug has always been there: http://gbdev.gg8.se/wiki/articles/RGBDS

>  Subtracting a numeric constant from a data structure symbol (rb, rw, ...) produces a parse error. It's still possible, however, to add a negative number.

**Comment by pinobatch** [comment]
I've made a couple test cases for this parser issue
[bug222test1.s.txt](https://github.com/rednex/rgbds/files/2526995/bug222test1.s.txt)
[bug222test2.s.txt](https://github.com/rednex/rgbds/files/2526996/bug222test2.s.txt)
