### ISSUE TITLE
Incorrect arithmetic when subtracting symbols

### ISSUE THREAD

**Issue by ekimekim** [rednex/rgbds#255]
The source:
```
foo = 3
bar = 2
PRINTV 10 - 3 - 2 - 1
PRINTV 10 - foo - bar - 1
```
Actual output:
```
$4$8
```
Expected output:
```
$4$4
```
When subtracting values from symbols (tested with both EQUate and set), it seems to apply order of operations incorrectly, resulting in (I'm speculating) a calculation like `10 - (3 - (2 - 1))`, instead of `((10 - 3) - 2) - 1` as is done with explicit numbers.

I also noticed that removing one of the two symbols values caused a syntax error.
Though I'm aware that syntax errors around subtraction is a long-standing issue, the potential to silently cause completely incorrect results is news to me, and highly problematic.

**Comment by AntonioND** [comment]
As far as I see, this isn't because of syntax problems, but about the associativity [1] of the operands in the parser. This has to be fixed, but I'm 100% sure that it is going to break some projects... This means that the version number will have to bump to 0.4.0, I guess.

[1] https://stackoverflow.com/questions/12876543/left-and-right-in-yacc

**Comment by AntonioND** [comment]
I've been thinking about how to fix this, and it's going to require quite a few modifications to the parser, so it will take some time.

**Comment by AntonioND** [comment]
Related to https://github.com/rednex/rgbds/issues/222

**Comment by AntonioND** [comment]
Fixed via https://github.com/rednex/rgbds/pull/311

I don't know why it hasn't been closed on its own.
