### ISSUE TITLE
Change in behaviour for jr @+constant

### ISSUE THREAD

**Issue by mattcurrie** [rednex/rgbds#259]
Source:

```
    jr @+$50
```

In 0.3.5 this is assembled as these bytes:

```
    $18 $4E
```

In 0.3.6 this is assembled as these bytes:

```
    $18 $4F
```

Is this an intentional change?  I'm guessing its related to the "Allow JR between sections." change in 0.3.6.

**Comment by AntonioND** [comment]
No, that's not intentional.

**Comment by Sanqui** [comment]
Anecdotally, I also noticed that `jr @` no longer caused the game to freeze.

**Comment by AntonioND** [comment]
What game?

**Comment by Sanqui** [comment]
I was testing while writing homebrew.

**Comment by AntonioND** [comment]
This is actually quite bad, it doesn't even work with constants. I'll fix it and add it to the release notes of 0.3.6. I don't think that many people will be affected, though. It only works when the result has to be calculated by the linker (labels, for example). In short, it works pretty much always, except when using `@` or numeric constants.

**Comment by mattcurrie** [comment]
Thanks Antonio.

In my disassembler I generate these type of instructions when there is a ```jr``` to an address that was not disassembled as the start address of an instruction (so there isn't a label to jump to).  I believe this is nearly always due to it disassembling some data bytes as code.

**Comment by AntonioND** [comment]
I've found a problem when fixing this.
```
ld bc,@
jp @
jr @

dw @
```
I can only fix one of the 2 groups with the current code, so I'll have to do more deep modifications to it...

**Comment by obskyr** [comment]
Perhaps while you're fixing this, you can allow `jr` to function with absolute addresses too?

While disassembling, I frequently find myself wanting to write placeholders like `jr $0350`, but that's currently not allowed. Instead of special-casing `jr @+[...]`, how about simply having `@+[...]` expand to an absolute address and have `jr` handle those too?

**Comment by AntonioND** [comment]
`rgbasm` doesn't evaluate `@`, it passes the reference to `rgblink`, and that's the one that actually evaluates it.

The problem is that `@` is evaluated at the position of the patch. For a `DW`, the position is the same place where `@` was in the source code. For any instruction, the `@` has to evaluate to the byte of the instruction, but it evaluates to the position of the offset byte (or the immediate). That's why it is off by one, and why it only happens with `@`, while labels still work.

The crash with constants is another issue, and that is easy to fix.

**Comment by AntonioND** [comment]
I've created a pull request that should take care of both problems.
