### ISSUE TITLE
RAM code and COPYSECTION

### ISSUE THREAD

**Issue by Sanqui** [rednex/rgbds#274]
This is a proposed solution to #272, but it's different enough that I'm making a separate issue.

I've implemented something that makes RAM code easy before, for [swapdump](https://github.com/Sanqui/swapdump).

Basically, I implemented two new rgbds features:
* A `-r` option to rgbasm which lets you put code in RAM (https://github.com/Sanqui/rgbds/commit/4f7b98fd383064fe749b92321c62ac7f0cb098d8)
* A `COPYSECTION` directive which creates a binary copy of an already-written section (https://github.com/Sanqui/rgbds/commit/eac57476c1b5acf54cfb05c138412e4e72058825)

Usage then follows:

```
SECTION "ram code", WRAM0[$C000]

RAMCode:
    jp RAMCode
```

This will not emit any bytes, but the section will be compiled, the space will be reserved and the labels will be calculated (resulting in a proper `jp $C000`)

```
COPYSECTION "ram code", ROMX[$4000], BANK[$1]
```

This will take the section output as "ram code" and create a new section with exactly the same data.  Since the WRAM section would never have been output, this is the way to actually place the generated opcodes in ROM, to be copied to RAM later.

Now, I don't know if this approach is sensible and I haven't tested it extensively, but should you like it, I can rebase and make a pull request.

**Comment by AntonioND** [comment]
I think it's sensible, but let's wait if there are other opinions.

**Comment by slembcke** [comment]
The ability to have a "data" section with the run/load addresses is something I've been missing from cc65 as well.

**Comment by pinobatch** [comment]
Is it ready to rebase?

**Comment by ISSOtm** [comment]
First, there is one assumption currently made in the codebase that I do not want to break: "two symbols owned by the same `SECTION` have a known offset between them."

Instead of a "symbase" keyword that modifies some sort of global state, I'd prefer a `LOAD`/`ENDL` block. `LOAD <type>[<addr>]` would have the semantics of `symbase <addr>` as defined above, and `ENDL` of `symbase @`. Such blocks would not be able to be nested. `<type>` would be required to be non-ROM (0 and X).

As for the implementation, here is an idea: when entering such a block, a new `SECTION` would be created, as if by `SECTION "COPYSECT@{__FILE__}:{__LINE__}", <type>[<addr>]` (`<addr>` being optional). All symbols created will be assigned to *that* `SECTION` instead of the current one. The "copy-section"'s size is updated with the `SECTION`'s. Once the `ENDL` is encountered, the state is reset.

**Comment by aaaaaa123456789** [comment]
I'd say this is OK.
