### ISSUE TITLE
[Feature request] Instruction aliases

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#276]
There are several instructions that require being written in odd ways, such as `ld hl, sp + 0`. There are other cases where simply having other ways of writing the same instruction might make the code clearer for some people.  
Therefore, it would be useful to add the following aliases for current instructions:

Proposed new alias | Current instruction | Rationale
--- | --- | ---
`ld hl, sp` | `ld hl, sp + 0` | The `+ 0` seems odd and unnecessary. While it _is_ encoded into the instruction, this is an implementation detail that can be concealed from the programmer harmlessly.
`ldh [c], a` | `ld [c], a` | The behavior of this instruction is more similar to `ldh` than `ld`, as it automatically fills in the missing byte with $FF. This also applies to other forms of the instruction, such as `ld a, [$ff00+c]`.
`ldio [c], a` | `ld [c], a` | Same as above.
`ld [$ff00 + c], a` | `ld [$ff00+c], a` | This is clearly a parsing bug. Same for `ld a, [$ff00+c]`.
`rst nz, $38` | `jr nz, @ + 1` | `rst $38` can be called conditionally this way, due to how instructions are encoded. However, there's no way of making this clear in the code, short of a comment. Note that this applies to any condition code, not just `nz`; however, it only works for `rst $38`.
`ld bc, $12, $34` | `ld bc, $1234` | Loading separate byte values into a register pair is a very common thing to do; this is so useful that we define a macro in the Pokémon repositories to do just this. However, the macro sometimes runs into problems, due to how expressions are evaluated. Incorporating it into the syntax of `ld` would solve this problem, without really creating any new ones; after all, the bytes are independent.
`add hl, sp, $46` | `ld hl, sp + $46` | This is the way instructions with separate operands and results are written in just about any other assembly language. This is the only such case in gbz80.
`ld [hl++], a` | `ld [hl+], a` | For similarity to C and the like. Same with other forms of this instruction.

Since all of these aliases would just allow alternate forms of existing instructions, none of them can cause backwards-incompatible changes.

Thoughts?

**Comment by ISSOtm** [comment]
I agree unconditionally with `ldh [c], a` and the other two.

I'm less a fan of `ld hl, sp`, since it feels like the instruction doesn't have any operands, which is something that I don't think should be concealed from the programmer.

I'm fairly even as `add hl, sp, $46` is now, but the new syntax could be nicer indeed.

Imo, meta-instruction stuff (such as `jr cond, @-1`, but also `jr @`, for example) isn't the job of the assembler, but rather of programmers, and would fit better into an include file such as [`hardware.inc`](https://github.com/tobiasvl/hardware.inc). So, I'm against `rst cond, $38`, and would rather leave it as a macro.

I'm not sure how `lb` can cause problems? ```
lb: MACRO
  ld \1, (\2) << 8 | LOW(\3)
ENDM
```

`ld a, [hl++]` would make sense, but that's just adding yet another alias for this instruction (`ldi a, [hl]`, `ld a, [hli]`, `ld a, [hl+]`, plus maybe other exotic forms). I think it's unnecessary, and `ld a, [hl+]` convery its meaning well enough.

**Comment by AntonioND** [comment]
In general I agree with @ISSOtm:
- `ld hl, sp`: I actually think it's better to be explicit and to know that the instruction uses 2 bytes. This isn't something like ARM, in which all the instructions are 32-bit wide. In that case it doesn't matter if you have aliases, in this case it hides the fact that there is a hidden 0 in the opcode. It's even worse if you consider that there is an actual `ld sp, hl` that doesn't take any more argument.
- `ldh [c], a`: Fair enough. We already have `ldh` anyway.
- `ldio [c], a`: I personally hate this mnemonic, but well, it's already there, so we might as well make it consistent...
- `ld [$ff00 + c], a`: Yes, this is a bug, it should be accepted.
- `rst nz, $38`: No, I don't think that pseudoinstructions are a good idea. Specially in this case, that a macro can do the job because there are no arguments more than a fixed address.
- `ld bc, $12, $34`: I'm a bit split here. The problem is that I don't want to add more variations of the current instructions. In the case of `ldh` and `ldio` I see it more as a "consistency fix" than adding something new. However, I see how this can be useful. Also, `bc` is a 16-bit destination, and the 2 elements would be 8-bit values, so I don't really like the syntax too much. I've already added warnings to things like `jp [hl]` because they are technically wrong, I don't want to add more cases like that in which in practice you get the meaning but they aren't 100% correct. I'd like to know where there are problems with macros that justify adding this.
- `add hl, sp, $46`: I'm not a fan of this. All ALU operations in the GB are spelled `op dst, src` where `dst = dst op src`. This would break this syntax for no good reason. Also, `ld hl, sp + $46` is more standard than your suggestion, and I'd like to have a syntax that is easier to recognize after reading a manual.
- `ld [hl++], a`: As @ISSOtm says, we have enough variations of this...

**Comment by AntonioND** [comment]
Why is that more clear than using `[hl]` for an access to memory and `hl` for immediate values? And why only for stores?

I think that there's no point in making up new instruction formats that nobody else uses or that don't appear in any document that describes the GB instruction set.

**Comment by ISSOtm** [comment]
I'm not sure how the first one is ambiguous, but for the third, I'd expect `0x34` to be interpreted as `0x0034`. Especially more confusing for the assembler, which couldn't distinguish the first 256 bytes and the last 256.

Also, as I said above, I'm generally against pseudo-instructions, especially if they can be implemented using macros (here ```
st: MACRO
  ld [\1], \2
ENDM
```)

**Comment by AntonioND** [comment]
That's what I meant, there is no way to know which one you need.

**Comment by lf94** [comment]
@AntonioND my proposal is if people don't want to track which version of `ld` to use. Because what is the point of tracking it in your head, when the assembler can do it for you? Please show everyone an example.

Alternatively we can have different `st*` instructions.

**Comment by AntonioND** [comment]
I don't think the current system is difficult to understand by any means, it is pretty standard. Actually, you have to keep less things in your mind because `ld` can do anything (load or store, from memory, from an immediate value...). If you want to access data, you use `$1234`, if you want to use the value at that address, you use `[$1234]`. You don't need to remember any mnemonic but `ld`:

```
ld a,$12
ld a,[$1234]
ld hl,$1234
```

This looks much easier to me than using different mnemonics for different cases of `ld`. Just take a look at Arm and what they did with `msr` and `mrs`, nobody ever remembers which is which. Having a generic mnemonic is more convenient. And more importantly, it is the standard way of doing assembly in the GB.

**Comment by aaaaaa123456789** [comment]
>nobody ever remembers which is which

Actually, `msr` is short for `move status, register`, and `mrs` is `move register, status`. Quite simple once you remember the acronym; same with `mcr` and `mrc`.

That being said, the main issue I see with that `st` alias is what to do with, say, `st (0x123456 >> 16), a`. Is that `ld [$0012], a` or `ldh [$ff12], a`?

**Comment by AntonioND** [comment]
I know, but when you are actually writing assembly code you are very likely to make a mistake because they are pretty inconvenient mnemonics. `mov` would have been much easier to remember in any case.

**Comment by AntonioND** [comment]
I've created https://github.com/rednex/rgbds/pull/277 with the additions I said a few messages away. I'm against any pseudo instruction. If I start adding some, more people will start asking new ones to be added, and this becomes a never ending story. I've only added the ones of the PR because the syntax is already there for `ld [$FF00+n],a`, so it's only fair to have it for `ld [$FF00+c],a`.

**Comment by AntonioND** [comment]
Another problem with `st` is that you only "fix" the issue for stores, but for loads you still have the same syntax, so what's the point?

**Comment by lf94** [comment]
Maybe instead of `st` we have `wr` and `rd`, meaning `write` and `read` to memory.

I agree that we should not change the standards that have been established over years because of material and other reasons. But I do think that  using `[]` is a sore spot because of what I mentioned above. What does [] mean on its own? Why would [a] be invalid, when [hl] is valid? With `rd` and `wr`, the targets always have to be 16-bit in size (hl, de, bc, any addresses).

**Comment by AntonioND** [comment]
But `[]` is the same, you can only use 16-bit values there (except for `[c]`, which is a syntax I don't like). That's why `[a]` isn't valid, but `[hl]` is valid, addresses are 16-bit values, so you can only use 16-bit values inside `[]`.

The problem is that I don't think that your suggestion is better. Using `[]` for indirection (or `()`, depending on the assembler) is pretty standard. By using `[]` you automatically know there is an access to memory.

Making up a lot of variations of the mnemonics is actually worse because you need to remember which is which (is `inci` the equivalent to `[]` or is it `inc`?). By using `[]` you don't need to remember that, it's explicit.

**Comment by AntonioND** [comment]
I guess that you simply like what I call "AVR syntax", in which each variation of an instruction has a different mnemonic. Most GB assemblers use Intel syntax, in which the mnemonic is overloaded and you specify the opcode by using helpers like `[]`.

I'm not going to change the way this assembler works because there is no point in doing so.

**Comment by lf94** [comment]
> I'm not going to change the way this assembler works because there is no point in doing so.

I figured, but it's still important to explore all avenues of discussion so we don't need to bring up more instruction alias conversation in the future :)

I didn't know AVR was like this, but I look forward to giving it a try :D 

To me, [a] should be valid if [hl] is valid, *when you think of a and hl as addresses themselves*. a = some magical address in memory. hl = some magical address in memory. It's a different way to think of registers. Likewise h would be some magical address in memory, as would l.

It would translate to: `[magic_address_for_cpu_register_a]` and `[magic_address_for_cpu_register_hl]`. I hope that is enough to get my point across. I will probably employ this in my own assembler one day because it seems to make more sense thinking like this.

**Comment by aaaaaa123456789** [comment]
Remember that whether a certain instruction is valid or not depends entirely on the hardware — you'll notice that, while `ld a, [hl]`, `ld a, [bc]` and `ld d, [hl]` are all valid, `ld d, [bc]` isn't. This is purely due to how the processor is built.

**Comment by AntonioND** [comment]
Uhm, yeah, of course. You have that problem regardless of the syntax you choose.

**Comment by AntonioND** [comment]
As discussed before, I'm not going to allow more pseudoinstructions or aliases because other people would come with other suggestions, and I don't want to deviate from the standard set used so far. The PR https://github.com/rednex/rgbds/pull/277 doesn't count because it's done for consistency.

**Comment by pinobatch** [comment]
The duplicate brought me here. After reviewing [optables](https://gbdev.io/gb-opcodes/optables/), I concur with not adding `ld hl, sp` on grounds of the principle of least astonishment. Adding it would produce confusingly asymmetric behavior in the flags, as `ld sp, hl` doesn't affect flags while `ld hl, sp+r8` is marked `0 0 H C`. In fact, the half-carry and carry come from adding the argument to the *low* byte of SP.
