### ISSUE TITLE
More descriptive section link error messages

### ISSUE THREAD

**Issue by PikalaxALT** [rednex/rgbds#284]
One quick example:
When the linker dies with error "Section FOO could not be loaded at $1337", it would be nice to see the name of the section that would overlap FOO (and this directly causes the error).

**Comment by PikalaxALT** [comment]
Also, RAM sections are allowed to overlap (not sure if it requires one of the sections to have size 0).  Is this intended?

**Comment by Ben10do** [comment]
Sounds like a helpful idea! 😄 It might take a bit of effort to implement, but I imagine this would save quite a lot of time.

---

Re: your second comment (I'll assume you're talking about fixing two RAM sections to the same address), I doubt that's intentional in general. However, if a section hasn't actually reserved any memory (even if it's been fixed at a position), I can see why that would avoid an error, even if they appear to overlap looking at your assembly.

While it's a fringe case, I can see why it might be helpful to catch these errors early, before you add more things to that section. If you can reproduce this (especially if it's with two non-empty sections), could you produce a minimum working example and add a separate issue?

**Comment by AntonioND** [comment]
Yes, it is an useful thing to have. However, the code isn't really ready for this, the file `src/link/assign.c` will need some rework.

Regarding the overlaps, maybe we could have a warning for all 0 byte sections instead. I don't think the linker should treat an empty region as a non-empty one and say there is an overlap when there really isn't. What about having an empty section just for a label? That's what they are doing here: https://github.com/rednex/rgbds/issues/233

**Comment by ISSOtm** [comment]
Does #434 improve / fix this?

**Comment by ISSOtm** [comment]
After merging #434 and testing the following simple program, it appears that the error message hasn't been improved.
```
SECTION "a", ROM0[0]
ds 2

SECTION "b", ROM0[1]
ds 1
```
The problem is that, in this trivial case, it's clear which sections overlap. But, if the section that fails to be placed is floating, trying to tell all the candidate locations that failed would result in an error log comparable to C++ template errors, which seem to be unanimously hated.
What would be a better solution?
(To be more down-to-earth, check function `placeSection` in `src/link/assign.c`)

**Comment by aaaaaa123456789** [comment]
Could you post example messages for the alternatives you suggest?

**Comment by ISSOtm** [comment]
The only case in which it seems possible to output something meaningful is when the failed `SECTION` has a fixed bank *and* address. Is that enough, though?

**Comment by aaaaaa123456789** [comment]
Better than nothing.

**Comment by ISSOtm** [comment]
And an absolute pain to implement!
