### ISSUE TITLE
[question/issue] rgbds generates strange code

### ISSUE THREAD

**Issue by smarmy** [rednex/rgbds#296]
I'm not sure if this is a bug or if I'm doing something strange (I'm pretty new  to gameboy dev/rgbds). I have a number of assembler files, each in section ROM0. I have one subroutine where rgbds seems to insert some additional garbage code, and I don't understand why:

Beginning of actual subroutine:
```
update_player::
	ld a, [player_y]
	ld [sprites], a	; Y
	ld a, [player_x]
	ld [sprites + 1], a	; X
	ld a, 0
	ld [sprites + 2], a	; Tile 0
	ld [sprites + 3], a	; Flags
```
Disassembled ROM:
```
Call_000_0061:
        ld a, [$c0a2]                             
        ld [$c000], a                             
        DB $fa                  ; ???                  

        and c                    ; ???          
        ret nz                   ; ???          

        ld [$c001], a                             
        ld a, $00
```

The `DB $fa`, `and c` and `ret nz` seems to come out of nowhere. Also, reverting the code that caused this I looked at the disassembly and there are other functions that get trash in them:

Correct:
```
Call_000_00c0:
jr_000_00c0:
        ld a, [hl+]                               
        ld [de], a                                
        inc de                                    
        dec bc                                    
        ld a, b                                   
        or c                                      
        jr nz, jr_000_00c0                        

        ret  
```
Incorrect:
```
Call_000_0061:
jr_000_0061:
        ld a, [hl+]                               
        ld [de], a                                
        inc de                                    
        dec bc                                    
        ld a, b                                   
        or c                                      
        DB $20                                    

        ld hl, sp-$37                             
```
If it matters, the code gets placed after the IRQ vectors but before the cartridge header.

I'm building with a makefile that looks something like:
```
LDFLAGS=-d -t
SRC=$(wildcard src/*.z80)
OBJ=$(SRC:src/%.z80=build/%.o)

$(TARGET): $(OBJ)
	rgblink $(LDFLAGS) -o $(TARGET) $(OBJ)
	rgbfix -v -p 0 $(TARGET)

$(OBJ): build/%.o : src/%.z80
	rgbasm $(INCLUDE) -o $@ $<
```

If you think this is a bug I could try to get a minimal example together.

**Comment by Ben10do** [comment]
That certainly does look funky, but it looks like it's the disassembler misunderstanding your ROM's layout.

`$FA` corresponds to the `ld a, [$XXXX]` instruction (which is immediately followed by that address), so rgbasm is clearly generating the correct machine code. From then onwards, the disassembler is trying to interpret the instructions with an improper alignment – so the address of `player_x`, `$C0A1`, is being interpreted as the `and c` (`$A1`) and `ret nz` (`$C0`) instructions (these bytes are flipped because addresses are little-endian).

I think the disassembler is assuming that the range `$0060` to `$0068` will be used as an interrupt handler (much like the 8-byte interrupt and `rst` handlers before it), even though there's much more space between there and the entry point at `$0100`.

You could mention this edge case to the developers of that disassembler, and suggest that they fix it. In the meantime or otherwise, try making sure that your code can't be placed in that interrupt handler. You could either specify a fixed address, or if you're not using the interrupt handler, you could fill it with `nop`s or `$FF` bytes.

**Comment by smarmy** [comment]
Alright, thanks! Yeah, so I guess the disassembler is at fault here rather than rgbds in that case.

The reason I started to look at the disassembly was because I had some other issues when calling my "update_player" routine so I wanted to look at the generated code and this weird disassembly jumped out at me, but I suppose I have some other problems in my code.

Will close this issue then!

**Comment by Ben10do** [comment]
Thanks!

Just in case you're not already using one: an emulator with debugging support might help you out in times like this. [bgb](http://bgb.bircd.org) is a popular one for Windows, and you can run it on Linux and macOS using [Wine](https://www.winehq.org).
