### ISSUE TITLE
Makefile commands silenced by default

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#377]
We had to debug a pretty annoying version issue (#376) while trying to figure out #375.

Why silence Makefile commands by default? This would've been better to debug if we saw the Makefile commands.

**Comment by AntonioND** [comment]
Why not leave them silenced and enable them when you have an issue? In general, I don't think that printing a lot of information is useful on its own. You should always print warnings and errors, and things that aren't expected, but invoking GCC is the normal thing to do. Too much information makes it hard to find actually useful information.

**Comment by ISSOtm** [comment]
Invoking GCC is a normal thing to do, and here it wasn't invoked. A lack of something signals something is wrong as much as the presence of a warning.

**Comment by AntonioND** [comment]
Would you have really seen that GCC wasn't being invoked for ``version.c``? I would have just seen some files being rebuilt and I wouldn't have even bothered to take a look at which ones.

**Comment by ISSOtm** [comment]
Call it personal preference, but I always read the commands being output.

**Comment by AntonioND** [comment]
Honestly, I find it hard to believe that you would have noticed a missing ``gcc version.c`` unless you were specifically looking for it. And enabling the verbose prints is as easy as doing ``make Q=``, you don't have to modify anything.

In the case of this project, this behaviour has been there since tag ``v0.0.1`` (I've just checked) so I think it makes more sense to leave it like this.

**Comment by ISSOtm** [comment]
I don't think suppressing useful output is a sensible default, but I won't change your mind.
