### ISSUE TITLE
Incorrect operator precedence

### ISSUE THREAD

**Issue by ISSOtm** [rednex/rgbds#380]
```
printn: macro ; See #368 on why I have to use this
    PRINTV \1
    PRINTT "\n"
endm
    printn 1 == 1 || 1 == 2
    printn (1 == 1) || (1 == 2)
```

This prints $0 then $1, it should print $1 twice.

([Source](https://rednex.github.io/rgbds/rgbasm.5.html#Integer_and_Boolean_expressions).)

**Comment by dbrotz** [comment]
The precedence levels in the source code don't match the order in the documentation. It's been that way since the first commit.

https://github.com/rednex/rgbds/blob/e895832b2b89cf341ef84ee43e70aaa41f002fed/src/ASM/YACCPRT1.Y#L377

`||`, `&&`, and `==` have the same precedence level for some reason. This could easily be fixed by just rearranging the precedence levels here.

https://github.com/rednex/rgbds/blob/master/src/asm/asmy.y#L540-L541

I hope that no one's code would be broken by this change.
