### ISSUE TITLE
`Docs` needs to be regenerated

### ISSUE THREAD

**Issue by IanBurgan** [rednex/rgbds#489]
The instruction set documentation site found here: https://rednex.github.io/rgbds/gbz80.7.html has an error with the `CP` and `SUB` instruction.

This error was fixed by 9c818ef, but the docs folder was never regenerated after the fix.

**Comment by ISSOtm** [comment]
(The actual resolution commit is 11b7052f9403944fef5fddf1d2815f37a9cf5c3b, that one is a merge commit :p)

The docs folder was not regenerated after that fix because that's only done on releases; the fix would be to have `master` man pages, but #458 hasn't been replied to (wrt implementation details). Feel free to bump that issue.

**Comment by IanBurgan** [comment]
Closing as this is contained within #458, Thanks
