### ISSUE TITLE
[Feature request] Section fragments

### ISSUE THREAD

**Issue by aaaaaa123456789** [rednex/rgbds#517]
(I sure seem to be making a lot of requests these days, don't I?)

Right now, two sections with the same name are automatically merged. This is great when it is the intended behavior, but I'd wager most of the time it's just an accident, and the outcome is most likely not the intended one. (Particularly when the sections have different attributes.)

What I'm requesting/proposing is a new section declaration, `SECTION FRAGMENT`, that would have this behavior; non-fragment sections would error out when duplicated instead. This way the behavior is retained (since people do rely on it), but cannot be accidentally triggered (removing a type of error that is very hard to detect). Section fragments' attributes should be subject to the same restrictions and merging as section union elements. Note that it would be impossible to declare a section both as a fragment and a union at once — this is intentional.

This request was inspired by C#'s `partial` keyword.

* * *

Examples:

(1) Right now, this would work and emit a ROM containing the bytes `01 02`:

```
SECTION "test", ROM0[0]
  db 1
SECTION "test", ROM0[0]
  db 2
```

By this request, that would fail to compile; the original behavior could be obtained with:

```
SECTION FRAGMENT "test", ROM0[0]
  db 1
SECTION FRAGMENT "test", ROM0[0]
  db 2
```

Note that it wouldn't be necessary to specify the `[0]` attribute both times.

(2) Merging attributes:

```
SECTION FRAGMENT "test", ROMX, ALIGN[3]
  db 1, 2, 3, 4, 5, 6, 7, 8
SECTION FRAGMENT "test", ROMX, BANK[1]
  db 8, 7, 6, 5, 4, 3, 2, 1
```

This would create a single section, with all 16 bytes as its contents, aligned to 8 bytes, in ROMX bank 1.

**Comment by JL2210** [comment]
> (I sure seem to be making a lot of requests these days, don't I?)

Maybe you could implement some yourself? It seems like other than me, ISSOtm is the only one who has been committing for a long time.

**Comment by aaaaaa123456789** [comment]
> > (I sure seem to be making a lot of requests these days, don't I?)
> 
> Maybe you could implement some yourself? It seems like other than me, ISSOtm is the only one who has been committing for a long time. The last one seems to be from January 8th: [6003be3](https://github.com/rednex/rgbds/commit/6003be3fae0aa4e03be7a2dcbb358f620666c526). The last one before that was in September: [f36a3d5](https://github.com/rednex/rgbds/commit/f36a3d5b2aab0fdfa9a1db0a10bc58677f18ac80). After that it's more active.

I really make requests when I come across a problem/unhandled thing; it's not like I expect them to be addressed immediately. I don't even have enough times for my own projects...

**Comment by ISSOtm** [comment]
It seems that this would be required to make RGBDS a back-end to SDCC. It has a `"GSINIT"` section defined across files, which is responsible for initializing memory at boot time; this section is scattered across files (since each file may have its own variables), thus link-time section concatenation is needed.

Link-time concatenation is currently impossible unless using a linker script, however this information is not conveyed by object files.

I would like to add that ordering cannot be guaranteed for this, at least in its current form. I am also unsure about giving address specifications to section fragments if their order cannot be guaranteed. If the user writes the following code:
```asm
SECTION FRAGMENT "hai", ROM0,ALIGN[1]
FuncTable::
    dw Foo, Bar, Foobar
```
they expect `FuncTable` to be aligned, not the whole section.

The problem with merging different attributes is that it's hard to resolve in a way that satisfies all alignment constraints optimally. Trying to concat all sections but also adding padding is much more complicated than it sounds like; take for example a 2-byte fragment fixed at $00FF, and a 255-byte fragment required to be aligned to 256 bytes. This *could* be turned into either a section fixed at $0000 and size 257 bytes, or one fixed at $00FF and size 511. (Note that the most optimal of these solutions size-wise may break if, say, another `SECTION` happened to be fixed at $0000. Taking that into account would be *very* complex.)

Here is my plan for this feature:
- Keep current behavior; but deprecate old-fashioned section concatenation.
- Implement `SECTION FRAGMENT`, which would work both at assembly time *and* link time.

**Comment by ISSOtm** [comment]
I'm marking this for 0.4.1 because I would like work to progress on making RGBDS the new GBDK back-end.

**Comment by aaaaaa123456789** [comment]
Guaranteeing fragment ordering _at assembly time_ would go far.

**Comment by ISSOtm** [comment]
That is absolutely possible, since there is a definitive order within the same file. Noted.
