### ISSUE TITLE
~ operator promotes binary EQU to 16-bit; [-Wtruncation] warning issued for legal 8-bit use (high bit set)

### ISSUE THREAD

**Issue by BlitterObjectBob** [rednex/rgbds#535]
If the ~ operator is used with a binary EQU with the high bit set, rgbasm will issue a warning [-Wtruncation]. This also happens with OR'd EQUs, as long as the resulting value has the high bit set before ~ is applied:

```
HIGH_BIT	EQU	%10000000
BIT_3		EQU	%00001000

	and	%01111111	; is fine
	and	~%01111111	; is fine
	and	HIGH_BIT	; is fine
	and	~(HIGH_BIT)	; gives warning: Expression must be 8-bit
	and	~HIGH_BIT	; gives warning: Expression must be 8-bit

	or	%01111111	; is fine
	or	~%01111111	; is fine
	or	HIGH_BIT	; is fine
	or	~(HIGH_BIT)	; gives warning: Expression must be 8-bit
	or	~HIGH_BIT	; gives warning: Expression must be 8-bit

	and	%01110111	; is fine
	and	~%01110111	; is fine
	and	HIGH_BIT|BIT_3	; is fine
	and	~(HIGH_BIT|BIT_3)	; gives warning: Expression must be 8-bit
```

rgbasm v0.4.0

**Comment by aaaaaa123456789** [comment]
`-Wtruncation` is trivially easy to trip whenever you do anything moderately unusual, because it assumes all values that happen to have high bits set must be signed integers with a dedicated in-range sign bit. In particular, values between $FFFFFF00 and $FFFFFF7F for 8-bit operands and between $FFFF0000 and $FFFF7FFF for 16-bit operands shouldn't be triggering _any_ warnings (or perhaps something only enabled by `-Weverything` for the people who _really_ want that extra check), but so far the warning continues to assume that if a value drops below zero, you must want to preserve the sign bit as well.

This has been very well known for a long time (see the original problem in #212 and the "code I don't like can't exist" discussion in #279).

**Comment by BlitterObjectBob** [comment]
`	and	~%10000000  ; gives the warning` fwiw (and for completeness in the examples)

**Comment by BlitterObjectBob** [comment]
`and %10000000 ^ $FF` is a good workaround. (Thanks ISSO!)
