### ISSUE TITLE
[Bug] Using `--nopad` without specifying the address of a section it can end up at in the wrong section.

### ISSUE THREAD

**Issue by daid** [rednex/rgbds#541]
Example:
```
SECTION "bank00", ROM0
  db $00

SECTION "bank01", ROMX, BANK[1]
  db $01
```
Compiled with `rgblink -x` will generate 2 bytes of ROM.

I would expect the $01 to end up at $4000.

Live demo with master:
http://daid.eu/dump/rgbds/#MoUQwgKgkg8gcgAgEQCMCGA7A1gBh0gGgQCUYBZHAKAQQBMUEASPSy0SWRVTXARkJLkAGkQBCAQTgBpANq8AutToNmvSkA

**Comment by ISSOtm** [comment]
This is actually correct behavior, since [`-x` implies `-t`](https://github.com/rednex/rgbds/blob/0793e9effe02e1ccd623704412aa750063f7d46b/src/link/main.c#L208), and so the `ROMX` section is converted to `ROM0`.

That said, @daid pointed out that he'd have expected the `ROMX` section to fail linking, as the documentation still pointed out... leading into c25b0be's fix.
