### ISSUE TITLE
IMPORT not importing

### ISSUE THREAD

**Issue by l0k1** [rednex/rgbds#76]
Apologies if this is just my newbishness, but...
I have a file, screens.asm, that has two labels:

```
Splash_Screen:
;...
Title_Screen:
```

In my main file, main.asm, I have:

```
IMPORT Splash_Screen
IMPORT Title_Screen
```

When running rgblink, I get the error: `rgblink: Unknown symbol 'Title_Screen'`
EXPORTing Splash_Screen and Title_Screen works, as does using GLOBAL.
Am I doing something wrong, or is IMPORT really not working?

**Comment by yenatch** [comment]
Imports are automatic, so you only need to export.

You can also export a label using `::`:
```
Splash_Screen::
; ...
Title_Screen::
```

**Comment by l0k1** [comment]
Thanks for the `::` tip. =] I prefer having it at the top of my file using `EXPORT` so I don't have to scroll through to see globals.

Per the docs, `IMPORT (or XREF) label[,label,...] This instructs the assembler to define label as if it were present in the current file but leave the address calculation to the linker.` 
I interpreted this to mean that if I `IMPORT label`, then I should have access to said label without needing to `EXPORT label` in the source file. This is how `IMPORT` works with all other symbols in RGBDS (except macros, but that's documented).
For example, say a file named "foo.asm" contained in it's entirety:
```
SOME_VALUE EQU $01
ANOTHER_VALUE SET $02
```
Without exporting, in "main.asm", I can
```
IMPORT SOME_CONSTANT
IMPORT ANOTHER_CONSTANT ;per docs, importing a SET is legal but undefined
```
and it'll work no problem.

Shouldn't this also work the same with labels?

**Comment by AntonioND** [comment]
This is a really old comment, but I'll answer as reference.

EXPORT makes rgbds add the name of the label to the object file, even if it is defined as local (e.g. `mylabel:` instead of `mylabel::`).

IMPORT makes rgbds not complain about labels that aren't defined in the file so that rgblink has to do it and, if it exists in a different object file, resolve the value.

As far as I see, the current version of rgbasm doesn't export values defined with SET or EQU.
